language: python
python:
- '3.5'
- '3.6'
- '3.7'
- '3.8'
install:
- pip install coverage coveralls
- python bootstrap.py
- "./bin/buildout"
script:
- coverage erase
- coverage run ./bin/test
- coveralls
deploy:
  provider: pypi
  on:
    tags: true
  user: __token__
  password:
    secure: XsEelvoDwCUbTDECloLK74mBqWmVlxLfqpqngUG/UDku2lP8PW1jEftG/o+tm1cKFudClDgKPylnvZFqbWQe/yFc4/K5UpNHT/HKnFQJIwY6U8qMZmhR/1gLhlPyl6IDKiwz9ipuF7Lmom+jdoffBXHvhIZNX7WNQNF59mwX9CfsD3Q+dhfSYxjFNX39MUT2dQ/j9ku48DaActr+9BcMCI7CCbmNtJSoKjyMMaSVl0oTCe4KWpUlEErQuYNbm2BgUrdTDgbp73EUkXyfC/D4515gj4oZeuYZ/tifcUvNJuEkgFz7KPXwjWCjqke8lD3brPQyI5vX6Wrw6NWicWF0UIn03WZl1eIJfVOmBy3nTuNQsIUNEPg2KWIdOx8mfm/symrJ/1dibLIsiUubRopXAFDNMrKDr2w0Fm5b1CJfaDJuC9YdJwgxLm9qgceScr00ZX/tTsI88Wn/yedNISokZJcwqkucdum5kRjvgxfH9234wTuaZs4wqS0/nO3s6UZjUgqM3kaBqvX/QMVvOOv78LgZL2/GBf1+NcE/gUfoHPVEWm/Xxh/W9OUzLNkzb0bjP4gk+IGm5bXRCoh+OmlACNExBZkePBWHkmZKAnIQbFJcixeXzk4hdMEH4YhAFy0hsuyP0/VZa2UPAZA2hmWLeMtVoowAs1bIPOtVbwFrOg0=
  distributions: sdist bdist_egg bdist_wheel
  skip_existing: true
